# Generated by Django 2.2.24 on 2023-03-12 03:39

from django.db import migrations


def upload_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        flats = Flat.objects.filter(owner=owner.owner)
        for



class Migration(migrations.Migration):
    dependencies = [
        ('property', '0014_auto_20230312_0422'),
    ]

    operations = [
        migrations.RunPython(upload_owners)
    ]
