# Generated by Django 2.2.24 on 2023-03-12 07:11

from django.db import migrations


def upload_owners_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        flats = Flat.objects.filter(owner=owner.owner)
        owner.flat.set(flats)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20230312_0902'),
    ]

    operations = [
        migrations.RunPython(upload_owners_flats)
    ]
