# Generated by Django 2.2.24 on 2023-03-12 08:33

from django.db import migrations

def new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230312_0911'),
    ]

    operations = [
        migrations.RunPython(new_building)
    ]
