# Generated by Django 2.2.24 on 2023-03-12 05:02

from django.db import migrations


def upload_owner_name(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(owner=flat.owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_owner'),
    ]

    operations = [
        migrations.RunPython(upload_owner_name)
    ]
