# Generated by Django 2.2.24 on 2023-03-13 21:38
import phonenumbers
from django.db import migrations


def reformat_phonenumber(phone_number):
    phone = phonenumbers.parse(phone_number, 'RU')
    if phonenumbers.is_valid_number(phone):
        return phone


def upgrade_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    old_format_numbers = Flat.objects.exclude(owners_phonenumber__isnull=True)
    for phone in old_format_numbers.iterator():
        phone.owner_pure_phone = reformat_phonenumber(phone.owners_phonenumber)
        phone.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_auto_20230313_2319'),
    ]

    operations = [
        migrations.RunPython(upgrade_phonenumbers),
    ]
