# Generated by Django 2.2.24 on 2023-03-13 22:13

from django.db import migrations


def upload_owners_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        flats = Flat.objects.filter(owner=owner.name)
        owner.flat.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230314_0004'),
    ]

    operations = [
        migrations.RunPython(upload_owners_flats)
    ]
