# Generated by Django 2.2.24 on 2023-03-12 02:22

from django.db import migrations
from django.db.models import  F


def upload_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber,
                                       owner_pure_phone=flat.owner_pure_phone)



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230312_0405'),
    ]

    operations = [
        migrations.RunPython(upload_owners)
    ]
